### ISSUE TITLE
bugs in README

### ISSUE THREAD

**Issue by Jakexxh** [ikeyasu/c3d-chainer#1]
### Download UCF11
wrong unrar command, it should be 
`$   unrar e UCF11_updated_mpg.rar`
### Converting to images
please delete the extra 's' in video_to_images.sh
`$ ls videos/*.mpg | parallel --no-notice -j8 ./tools/video_to_image.sh  {}`
### Making ignored dir
please delete the extra mv command behind the xargs
`$   grep '^[0-9] ' ../counts | cut -d ' ' -f 2 | xargs -I '{}' mv {} ../ignored`
### Unqualified images
the width of some images in folder `ucf11_160x120/images/` and `ucf11_160x120/tests/` is smaller than 160. Please delete or regenerate these images, otherwise it will cause errors.

**Comment by blackLYH** [comment]
## Unqualified images
the README say that
$Resize to 160x120 (half).

```
$ ls videos/*/*.jpg | parallel -j20 'convert -resize 160X120 {} `echo {} | sed "s/videos/ucf11_160x120\/images/"`'
```
it maybe cause the width of some images in folder ucf11_160x120/images/ and ucf11_160x120/tests/ is smaller than 160. 

### please add the extra '!' behind the 160X120.
```
$ ls videos/*/*.jpg | parallel -j20 'convert -resize 160X120! {} `echo {} | sed "s/videos/ucf11_160x120\/images/"`'
```

**Comment by ikeyasu** [comment]
Thank you both!
I will fix them very soon.

**Comment by ikeyasu** [comment]
I updated README. Thank you!
https://github.com/ikeyasu/c3d-chainer/commit/74598ecd102cbcc8a8f3985e96f8c7631834c462
